version: "3.8"

services:
  banco:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=bX42V5oOZ7Bg
      - MSSQL_PID=Developer
    ports:
      - "5433:1433"
    volumes:
      - /var/opt/mssql
    networks:
      - tarefas_app

  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=usuario
      - RABBITMQ_DEFAULT_PASS=z8YR1jHtZtiB
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.7
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tarefas_app

  consul:
    image: consul:1.8.0
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    networks:
      - tarefas_app

  api-gateway:
    container_name: api-gateway
    build:
      context: ../
      dockerfile: src/ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    networks:
      - tarefas_app
    depends_on:
      - consul

  tarefas:
    container_name: tarefas
    build:
      context: ../
      dockerfile: src/Servicos/Tarefas/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__Default=Server=banco;Database=TarefasDb;User Id=sa;Password=bX42V5oOZ7Bg;
      - EventBusConfig__Host=rabbitmq
      - EventBusConfig__Porta=5672
      - EventBusConfig__Usuario=usuario
      - EventBusConfig__Senha=z8YR1jHtZtiB
      - ConsulConfig__UrlConsul=http://consul:8500
      - ConsulConfig__NomeServico=tarefas
    ports:
      - "8081:80"
    networks:
      - tarefas_app
    depends_on:
      - banco
      - rabbitmq
      - consul

  usuarios:
    container_name: usuarios
    build:
      context: ../
      dockerfile: src/Servicos/Usuarios/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__Default=Server=banco;Database=UsuariosDb;User Id=sa;Password=bX42V5oOZ7Bg;
      - EventBusConfig__Host=rabbitmq
      - EventBusConfig__Porta=5672
      - EventBusConfig__Usuario=usuario
      - EventBusConfig__Senha=z8YR1jHtZtiB
      - ConsulConfig__UrlConsul=http://consul:8500
      - ConsulConfig__NomeServico=usuarios
    ports:
      - "8082:80"
    networks:
      - tarefas_app
    depends_on:
      - banco
      - rabbitmq
      - consul

networks:
  tarefas_app:
    driver: bridge
